### ISSUE TITLE
Flowtype lib defs do not exist in published npm package

### ISSUE THREAD

**Issue by stefan-giangiuliani** [uber/nebula.gl#106]

**Comment by supersonicclay** [comment]
@ibgreen is this something you have setup for deck.gl yet?

**Comment by NameFILIP** [comment]
we recently had a bug in production after `featureIndex` was renamed to `featureIndexes`. Having correct flow types would have caught it. Would it be possible to prioritize fixing publishing of types (since the codebase already contains them)?

**Comment by NameFILIP** [comment]
TODO:
* copy / paste the source file and rename each file .js.flow
* add an index.js.flow in dist that points to the source

**Comment by NameFILIP** [comment]
Some related info:
Old article: https://medium.com/netscape/shipping-flowtype-definitions-in-npm-packages-c987917efb65
Example: https://github.com/uber-web/baseui/blob/master/package.json#L26

**Comment by ibgreen** [comment]
> @ibgreen is this something you have setup for deck.gl yet?

No. nebula.gl and react-map-gl are the only vis.gl projects that use flow. Other projects like deck.gl have no plans to do so, so those projects would need to "manually" define flow types for consuming applications (something we are interested in but have not gotten around to).

I am actually not sure if react-map-gl is currently taking any steps to publish flow types as part of its npm package, but it would make a lot of sense to 1) publish them and 2) publish the same way in nebula.gl and react-map-gl. @Pessimistress
