### ISSUE TITLE
Replace hacky event handling

### ISSUE THREAD

**Issue by supersonicclay** [uber/nebula.gl#126]
Get rid of hacky pointer event handlers in `EditableLayer`. Instead, use the new events exposed in deck.gl 6.3.

Some pseudocode of it working elsewhere:

```js
class MyLayer extends CompositeLayer {
  constructor(props) {
    // NOTE: hacky, we shouldn't inject callbacks in this way.
    // PS1: onDrag, onClick, onHover need to be methods of MyLayer instead of arrow functions
    // Otherwise they will become undefined in the following callbacks
    // => I don't know why :(
    // PS2: these injections need to be happened before super(props);
    props.onDrag = (info, event) => info.layer.onDrag(info, event);
    props.onClick = info => info.layer.onClick(info);
    props.onHover = info => info.layer.onHover(info);
  }
}
```

**Comment by georgios-uber** [comment]
This will require everyone to upgrade to deck.gl 6.3. Let's wait some time before we do this.

**Comment by IgorWilbert** [comment]
Hey guys! Is it still too soon for us to do this?

**Comment by supersonicclay** [comment]
The challenge is that nebula relies on these callbacks being called regardless if something was picked on that layer or not. Currently the pointer even callbacks are only triggered if something was picked on that layer.

**Comment by georgios-uber** [comment]
Deck has improved their event handling.
@ibgreen @Pessimistress what is the deck status on this?

**Comment by Pessimistress** [comment]
Is it just the click event that you need regardless of picked layer?

**Comment by supersonicclay** [comment]
In certain states we listen to pointer move regardless of picks also.

**Comment by Pessimistress** [comment]
Eventually what you're trying to do cannot be encapsulated in the "layer" concept. This may sound awkward but you can render a transparent layer that covers the whole screen to capture click and pointer move.

**Comment by supersonicclay** [comment]
It may make more sense to look at implementing event handling in a deck.gl controller rather than continuing to encapsulate in a single composite layer.

The controller and layer would need to collaborate on the data though. Are there other examples of deck.gl controllers that share data with layers? Or are most of the uses of controllers for manipulating the viewport?
