### ISSUE TITLE
Consistent component composing hierarchy in Nebula and Deck

### ISSUE THREAD

**Issue by vnugent** [uber/nebula.gl#139]
#### Feature request
Make MapGL a child component of Nebula similar to Deck.gl or the other way around.

At the moment Getting-started docs show two different approaches:

### [Deck](http://deck.gl/#/documentation/getting-started/using-with-react?section=adding-a-base-map)
The base map `<StaticMap/>` is a child of `<DeckGL/>` component. 
```  
    <DeckGL
        initialViewState={initialViewState}
        controller={true}
        layers={layers}
      >
        <StaticMap mapboxApiAccessToken={MAPBOX_ACCESS_TOKEN} />
      </DeckGL>
```
### [Nebubla](https://neb.gl/#/documentation/get-started/basic-usage)
`<MapGL/>` is the parent of Nebula
```
      <MapGL {...viewport} onChangeViewport={this._onChangeViewport}>
        <Nebula
          ref={nebula => (this.nebula = nebula || this.nebula)}
          {...{ layers, viewport }}
        />
      </MapGL>
```
#### To Do List 
  - [x] Add label and assign to milestone
  - [ ] Coding
  - [ ] Doc update
  - [ ] Test

**Comment by supersonicclay** [comment]
You can see an example [here](https://github.com/uber/nebula.gl/blob/master/examples/deck/example.js#L438).

**Comment by georgios-uber** [comment]
Removed Nebula component.
