### ISSUE TITLE
onClick event not fired on EditableGeoJsonLayer

### ISSUE THREAD

**Issue by ConnectedWanderer** [uber/nebula.gl#146]
I'm trying to reproduce this example : https://neb.gl/#/examples/editable-geo-json/points. However, it seems that the onClick event is never triggered on the layer.

Here is an example : [codesandbox](https://codesandbox.io/s/5mvq851lx4?module=%2Fsrc%2FMapComponent.js)

Is this part of the docs not updated maybe ?

**Comment by georgios-uber** [comment]
Let me check.

**Comment by georgios-uber** [comment]
@ConnectedWanderer You can use **deck.gl**'s `onLayerClick` function.
I also cleaned up the code to remove `nebula.gl-react` (is only needed for the other examples).
I have updated the code here https://codesandbox.io/s/43k1r67jr7

Let's leave this issue open, I will later investigate why onClick didn't work on the first place.
Thanks for taking the time to report this issue 👍

**Comment by ConnectedWanderer** [comment]
Thank you for your quick answer and your help  👍
