### ISSUE TITLE
[INFO] EditableGeoJsonLayer dissapears while editing and panning

### ISSUE THREAD

**Issue by carlostxm** [uber/nebula.gl#148]
Hi,

Firstly thanks for the work you are doing, it's being very helpful for my project.

I'm having a problem with the EditableGeoJsonLayer which dissapears while drawPolygon mode is set and the map is panned.

I've inspected the layer using Seer and I've seen that the layer instance stays when the map viewport changes but handlers are removed. I'm not able to understand what is happening since only happens in my application. I've created a similar use case in codesandbox but it works fine.

![draw-polygon](https://user-images.githubusercontent.com/11058795/50597698-9a727e00-0ea8-11e9-9ae4-5e65858fa938.gif)

Anyone could give a hint about what is happening?

Thanks,

Carlos.

**Comment by georgios-uber** [comment]
Hi,
Thanks for using our library.

We capture the events and prevent them from going to the mapbox. Can you provide any more details? Are you using CSS `pointer-events` to change something?

@supersonicclay Any ideas?

**Comment by supersonicclay** [comment]
Nebula.gl and deck.gl use JavaScript shallow object comparison when determining if there are changes. It could be you are perhaps creating a new object on every render cycle. And nebula clears the tentative feature when some props change (e.g. `modeConfig`, `mode`)

For example, this will cause that behavior:

```
render() {
  const modeConfig = {}
  const layer = new EditableGeoJsonLayer({
    // ...
    modeConfig: modeConfig,
    // ...
  });

  // ...
}
```

**Comment by carlostxm** [comment]
Ups, yes that's the problem. I was setting selectedFeatureIndexes to [] in every render so a new array was being created. Thanks!
