### ISSUE TITLE
EditableGeoJsonLayer in drawPolygon mode crashes when point or line is created

### ISSUE THREAD

**Issue by carlostxm** [uber/nebula.gl#153]
Hi,

I'm trying to implement a selection utility over a DeckGL polygon layer using the EditableGeoJsonLayer. The idea is that the user create a polygon whose contour coordinates are used to filter the elements that are inside it. The functionallity works nice, but I have detected one bug which I describe below.

#### Describe the bug
When EditableGeoJsonLayer in mode 'drawPolygon' is attempted to be finished with a point or a line (first double click or click and double click), the layer crash and stays in an unresponsible state throwing the following error (in some cases):

<img width="632" alt="2019-01-25 09_34_52-devtools - localhost_8008_" src="https://user-images.githubusercontent.com/11058795/51734359-8fb0a080-2084-11e9-8e58-01d66310f716.png">

#### Actual Result
Error is thrown, layer stays unresponsible not allowing to react to this state.

#### Expected Result
Layer should verify the polygon and not stay unresponsiv. Some callback should be called in order to do something when this happen.

#### Reproduce Steps
Please, find a example in the following codesandbox. 
Set your own MAPBOX_TOKEN.

[![Edit Nebula.gl issue](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/x7o87w6xz4)

#### Screenshots
When a point or a line are drawn the layer stays unresponsive, not responding to click events. (In this case no error is thrown)

Users draw a point:
![draw-polygon-line](https://user-images.githubusercontent.com/11058795/51734877-1fa31a00-2086-11e9-95d5-bee9bfca05e8.gif)

User draws a line:
![draw-polygon-point](https://user-images.githubusercontent.com/11058795/51734859-10bc6780-2086-11e9-8954-f604b2593ddf.gif)

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by supersonicclay** [comment]
Sorry for the inconvenience. We fixed compatibility with deck 6.3 in nebula 0.8. So, you can downgrade deck to <6.3 or upgrade nebula to 0.8.

#149

**Comment by carlostxm** [comment]
I upgraded nebula.gl to 0.8 and it works like a charm with deck.gl 6.3.9. Thanks!
