### ISSUE TITLE
Bump nebula dependency on deck/luma to 6.4.0

### ISSUE THREAD

**Issue by romaxa** [uber/nebula.gl#159]
Nebula depends on deck/luma 6.4.0, so it should be explicitly specified in nebula package.json

**Comment by lxe** [comment]
Is this still relevant? Does luma 6.4.2 work?

**Comment by snosenzo** [comment]
The ScatterplotLayer inside of the `editable-geojson-layer.js` has a warning because of deprecated props. It also has a display bug because of those props.

**Comment by georgios-uber** [comment]
Fixed.
