### ISSUE TITLE
Dont require Deck.gl as a dependency 

### ISSUE THREAD

**Issue by baxter1707** [uber/nebula.gl#168]
Is it possible to remove Deck.gl as a dependency? Is there a specific reason for requiring it?

Sorry for poor formatting. First time submitting an issue!

**Comment by supersonicclay** [comment]
The main class of nebula.gl: `EditableGeoJsonLayer` is implemented as a deck.gl layer. Is there something in particular you're looking to use of nebula that doesn't require deck?

**Comment by georgios-uber** [comment]
Yes, we need deck.gl but we could make it a peer dependency

**Comment by georgios-uber** [comment]
Done.
