### ISSUE TITLE
Draw doesn't work on Safari and iOS

### ISSUE THREAD

**Issue by baxter1707** [uber/nebula.gl#169]
#### Describe the bug
When clicking on the map using an iOS device onLayerClick seems to fire, but points are not drawn.
#### Actual Result
No points drawn
#### Expected Result
Points to show up on map.
#### Reproduce Steps
Run map, with Nebula.gl on iOS device. When you try and draw something no shapes or points are dropped.
#### To Do List 
  - [x] Add label and assign to milestone
  - [x] Coding
  - [ ] Test

**Comment by supersonicclay** [comment]
Safari apparently doesn't support `pointerdown` event. We'll have to look at using [hammerjs](https://hammerjs.github.io/) or [mjolnir](https://github.com/uber-web/mjolnir.js/).
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/pointerdown_event

**Comment by contra** [comment]
@supersonicclay Have you had a chance to look into this? If you haven't started I can send a PR for this.

**Comment by markcarroll** [comment]
The issue is not limited to Safari on iOS. Editing does not work on desktop Safari as well.

**Comment by supersonicclay** [comment]
I haven't started a code fix yet. But the plan is to refactor `EditableLayer` to use [mjolnir](https://github.com/uber-web/mjolnir.js/) instead of registering window pointer event handlers direct.y.
