### ISSUE TITLE
ESC should cancel drawing

### ISSUE THREAD

**Issue by supersonicclay** [uber/nebula.gl#171]
### Feature request

There should be an easier way to cancel drawing.

#### Repro Steps

Enter `drawPolygon` mode. Click a few points. Hit Escape on keyboard.

#### Actual

Does nothing. No clear way to start over with the polygon.

#### Expected

Clear the tentative feature. Start over with drawing. Should work with all the draw modes.

#### To Do List 

  - [x] Add label and assign to milestone
  - [ ] Coding
  - [ ] Doc update
  - [ ] Test

**Comment by georgios-uber** [comment]
Is this fixed by new handlers logic?

**Comment by FKSI** [comment]
Is there any news on that front? :)
