### ISSUE TITLE
Make HTML overlay independent on nebula

### ISSUE THREAD

**Issue by romaxa** [uber/nebula.gl#179]
#### Target Use case
Use deck layers with HTML/React components and don't have dependency on react-map-gl or nebula.gl

#### Proposed feature
Probably makes sense to move nebula HTML overlay to become as independent deck.gl layer

**Comment by georgios-uber** [comment]
@ibgreen what do you think?

**Comment by ibgreen** [comment]
Well we have two systems for setting up react context for overlays, one in react-map-gl and one in nebula.gl, but currently none in deck.gl/react.

I wonder if we could just standardize and document the way we set up the React context, and do it the same way in all three libs.

Then all these overlays could be used interchangeably with any of the libs.

@Pessimistress FYI

**Comment by georgios-uber** [comment]
https://github.com/uber/nebula.gl/pull/182/files

**Comment by georgios-uber** [comment]
#182
