### ISSUE TITLE
EditableGeoJsonLayer can't add points on mobile

### ISSUE THREAD

**Issue by MattReimer** [uber/nebula.gl#181]
#### Describe the bug

On my android phone (in chrome) when I click edit on  <https://nebula.gl/#/> I can see different coloured dots on the midpoints of lines so that I can subdivide that line

#### Actual Result

I can add points on a desktop using a mouse but when I switch to mobile I can no longer add points using touch

#### Reproduce Steps

Here's my code sandbox
https://codesandbox.io/s/9qo3l476po

And the subsequent URL I used on my Android phone:

https://9qo3l476po.codesandbox.io/

#### To Do List 
  - [x] Add label and assign to milestone
  - [x] Coding
  - [ ] Test

**Comment by sdll** [comment]
The issue is covered here: https://github.com/uber/nebula.gl/issues/169
