### ISSUE TITLE
'isEditingHandles' only defined on editing handles 

### ISSUE THREAD

**Issue by matthrice** [uber/nebula.gl#19]
From `editableGeoJsonLayer.js`:

```
getPickingInfo({ info, sourceLayer }) {
    if (sourceLayer.id.endsWith('-edit-handles')) {
      // If user is picking an editing handle, add additional data to the info
      info.isEditingHandle = true;

      if (info.object) {
        info.positionIndexes = info.object.positionIndexes;
      }
    }

    return info;
  }
```

`isEditingHandle` is only defined on the edit handle layer, but it should be defined on all nebula layers right? Also this property isn't checked against in `_onLayerClick` in the example. This causes some weird behavior in the example when clicking on points.

**Comment by georgios-uber** [comment]
Please note that we are changing the API. `editableGeoJsonLayer` uses the new way.
