### ISSUE TITLE
getLineWidth question

### ISSUE THREAD

**Issue by baxter1707** [uber/nebula.gl#196]
When using:  
getLineWidth on EditableGeoJson is it possible to change the return value from meters, to pixels?

I think on a Deck.gl layer you can use the 
lineWidthUnits : "pixels" 
properties to change this, but it doesnt look like that is supported on EditableGeoJsonLayer.

Thank you!

**Comment by ibgreen** [comment]
FWIW, the `...Units` props allowing selection between meters and pixels are new additions to deck.gl v7.0 which is still in beta release.

To the extent that `EditableGeoJsonLayer` inherits from deck.gl layer, this may be automatically supported once nebula fully upgrades to deck.gl v7?

**Comment by georgios-uber** [comment]
Yes, it will be supported when we switch to Deck 7.0 (by the end of month).

**Comment by baxter1707** [comment]
Awesome, thank you for the quick response, and awesome work!

**Comment by supersonicclay** [comment]
This is now supported.
https://nebula.gl/docs/api-reference/layers/editable-geojson-layer
