### ISSUE TITLE
minified js 

### ISSUE THREAD

**Issue by SymbolixAU** [uber/nebula.gl#206]
#### Feature request

Do you plan on making a `nebula.min.js` file available? Nebula would make a good addition to my `R` implementation of Deck.gl ([mapdeck](https://github.com/SymbolixAU/mapdeck))

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Doc update
  - [ ] Test

**Comment by supersonicclay** [comment]
At this time, we are publishing the source to npm. You can look at pulling it into your project with a JavaScript module bundler, like [webpack](https://webpack.js.org/).

**Comment by ibgreen** [comment]
Some context: In deck and luma we create script "bundles" during the build/publish process and add them to the npm module.

These scripts can then be use in HTML `<script>` statements via `unpkg.com`:

- https://unpkg.com/@deck.gl/core@7.0.0/dist.min.js
- https://unpkg.com/@deck.gl/core@7.0.0/dist/dist.dev.js

It would be a relatively modest amount of work to add these to the nebula build process.

**Comment by SymbolixAU** [comment]
Thanks @ibgreen; I'll continue working under the assumption this won't be implemented (at least short-term).
