### ISSUE TITLE
Edit feature attributes

### ISSUE THREAD

**Issue by rkertesz** [uber/nebula.gl#216]
I have been looking for a native way to edit feature attributes. Moving features is useful too but most of all I need to change something from 20mph to 40mph or 20ft wide to 40ft wide. Is this something that can already be done using deck or nebula functions?

**Comment by supersonicclay** [comment]
Are you referring to changing values within the `properties` attribute of your GeoJSON?

**Comment by rkertesz** [comment]
@supersonicclay That is Correct. It seems like being able to edit properties of existing features is good extension of a platform designed for editing geometry but perhaps you have a better recommendation

**Comment by supersonicclay** [comment]
Having react components (e.g. toolbar, modals, etc) is something we've considered doing with nebula. But it is likely something that is going to be more tailored to specific applications. Some may prefer modals, some sidebars, etc. So building something generic and flexible can be a challenge.

At this time, we're focused on nailing the canvas drawing aspect of geometry editing. But for now, property editing is something that can be accomplished with react and built atop nebula. Perhaps it would be interesting to add as an example.
