### ISSUE TITLE
selection layer broken after updating

### ISSUE THREAD

**Issue by contra** [uber/nebula.gl#221]
#### Describe the bug

After updating to nebula 0.12.0 + deck.gl 7.x, the SelectLayer rectangle select throws an error.

#### Actual Result

```
Uncaught TypeError: this.context.layerManager.pickObjects is not a function
    at SelectionLayer._selectRectangleObjects (selection-layer.js?8634:60)
    at Object.onEdit (selection-layer.js?8634:150)
    at EditableGeoJsonLayer.onLayerClick (editable-geojson-layer.js?1375:442)
    at EditableGeoJsonLayer._onPointerUp (editable-layer.js?3197:232)
    at HTMLCanvasElement.d (raven.js:444)
```

Actual stack is line 60 in selection-layer.js

#### Reproduce Steps

Use SelectLayer w/ deck.gl 7.x and nebula.gl 0.12.0

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by contra** [comment]
Ah, after looking through the code to start a PR it seems it has already been fixed: https://github.com/uber/nebula.gl/commit/8e9c2ec8d7cf4ca7050909ed826eb847d5e2cd9c

Can this be published?

**Comment by georgios-uber** [comment]
Sure, let me make a build

**Comment by contra** [comment]
@georgios-uber Thanks!

**Comment by georgios-uber** [comment]
0.12.1
