### ISSUE TITLE
NullPointerException with closure-compiler via shadow-cljs

### ISSUE THREAD

**Issue by deadghost** [uber/nebula.gl#244]
I know this is a long shot because the issue is many layers deep. I'm compiling clojurescript to js via shadow-cljs. shadow-cljs uses the closure-compiler. The closure-compiler is throwing NPE with `nebula.gl`. Reproduction of error(in clojurescript): https://github.com/deadghost/shadow-npe.

I've asked @thheller, the author of `shadow-cljs` about this and he said it looks like a closure-compiler bug. This is a list of open closure-compiler NPE issues: https://github.com/google/closure-compiler/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+nullpointerexception. The reasons for NPE aren't super long and it might be possible to slightly modify `nebula.gl` or the offending dependency library to play nice with closure-compiler.

I'm just throwing this out there in the off chance someone on the `nebula.gl` team happens to know what's going on and how to fix it.

**Comment by georgios-uber** [comment]
Sorry, I don't know anyone using closure-compiler with nebula.
