### ISSUE TITLE
react-map-gl-draw: state is not initialized properly from props on mount in ModeHandler

### ISSUE THREAD

**Issue by macobo** [uber/nebula.gl#274]
#### Describe the bug

Try to initialize editor in `mode={'DRAW_PATH'}`. 

```
type State = {
  features: any[],
  mode: string,
}

export class FieldSplittingMap extends PureComponent<Props, State> {
  state = {
    mode: EditorModes.READ_ONLY,
    features: [],
  }

  render() {
    return (
      <ConnectedBaseMap {...this.props}>
        <Editor
          clickRadius={12}
          onSelect={this.onSelect}
          onUpdate={this.onUpdate}
          mode={EditorModes.DRAW_PATH}
          {...this.state}
        />
      </ConnectedBaseMap>
    )
  }
```

#### Actual Result

You cannot draw a line.

#### Expected Result

You cannot draw a line.

#### Reproduce Steps

Bug comes from this file constructor: https://github.com/uber/nebula.gl/blob/master/modules/react-map-gl-draw/src/mode-handler.js#L71-L86

Namely, when props change, ModeHandler calls some internal handlers which set up mode, features and other props. If user passes in props "in the beginning" e.g. to draw a line or to edit a feature, the library will appear to be doing nothing.

Users need to work around this by moving the mode to their wrapper component internal state and using e.g. `setTimeout` in `componentDidMount` to make the library work.

```

type State = {
  features: any[],
  mode: string,
}

export class FieldSplittingMap extends PureComponent<Props, State> {
  state = {
    mode: EditorModes.READ_ONLY,
    features: [],
  }

  // :KLUDGE: Work around react-map-gl-draw only working as modes/props change, not on initial render.
  componentDidMount = () => {
    setTimeout(
      () =>  this.setState({ mode: EditorModes.DRAW_PATH }),
      500
    )
  }

  render() {
    return (
      <ConnectedBaseMap {...this.props}>
        <Editor
          clickRadius={12}
          onSelect={this.onSelect}
          onUpdate={this.onUpdate}
          {...this.state}
        />
      </ConnectedBaseMap>
    )
  }
}
```

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by macobo** [comment]
Related: We're trying to use editor within existing flows where user can edit features that originate from outside of react-map-gl-draw. We haven't had much success yet.

On the positive side, the lower layers of the library seem great! SVG is an elegant solution here for how to do editing.

However, here's a list of various grievances that we've run into so far.

- componentWillUpdate loop does not work very well. We need to do manual hacking to even get selectedFeatureIndex state to be set correctly - if you update `props.features` and `props.selectedFeatureId` at the same time it does not get updated
- Related: Some of the code is very reliant on 'demo' usage and throws errors when mouse hasn't moved between setting features and setting selected feature index.
- Stateful vs stateless component - it would be nice if we could properly tie the component to our redux flows. The comment by @macrigiuseppe under this PR is 100% correct: https://github.com/uber/nebula.gl/pull/257 
- Feature dragging is a weird feature - it has so far caused more confusion than actually created good UX. Most of the time it gets used when trying to add a new vertex to an edge.
- Creating "conforming" features for react-map-gl-draw is hard, as you need to follow two undocumented and non-standard requirements 
  - your features have prop `renderType` set correctly
  - your features have prop `id` - not sure why the library isn't using the geojson standard `feature.id` attribute instead?

**Comment by macrigiuseppe** [comment]
@macobo I was able to set the initial editor mode using redux. You can checkout my PR here: https://github.com/keplergl/kepler.gl/pull/595

**Comment by xintongxia** [comment]
@macobo apologize for late response. Thanks for the details reviews. Recently I made some improvement of the `react-map-gl-draw`, hope it can help address some of your concerns.

> componentWillUpdate loop does not work very well. We need to do manual hacking to even get selectedFeatureIndex state to be set correctly - if you update props.features and props.selectedFeatureId at the same time it does not get updated

See the reply to `Stateful vs stateless component`.

> Stateful vs stateless component - it would be nice if we could properly tie the component to our redux flows. The comment by @macrigiuseppe under this PR is 100% correct: #257

The [new API](https://github.com/uber/nebula.gl/tree/master/modules/react-map-gl-draw#options) provides stateful and stateless versions by the following way:

```
features (Feature[], Optional) - List of features in GeoJson format. If features are provided from users, then react-map-gl-draw respect the users' input, and therefore ignore any internal features. But if features are not provided, then react-map-gl-draw manages features internally, and users can access and manipulate the features by calling getFeatures, addFeatures, and deleteFeatures.
```

`selectedFeatureIndex` should also respect user's input over internal managed state. But currently it has a bug, I'll fix it soon.

> Feature dragging is a weird feature - it has so far caused more confusion than actually created good UX. Most of the time it gets used when trying to add a new vertex to an edge.

I agree with you on this. Right now when user click/drag a vertex, it is considered as dragging vertex, when click/drag inside a polygon, it is considered as dragging the feature. When user click on an edge, it is considered as adding an vertex to the edge.

Some of the use cases might only need adding vertex feature, so I am thinking to add more properties to allow user to turn on/off the adding vertex to an edge / dragging and son on. I'll create an issue to elaborate this.

> Creating "conforming" features for react-map-gl-draw is hard, as you need to follow two undocumented and non-standard requirements

> your features have prop renderType set correctly

`renderType` is supposed to be used for styling, I mentioned briefly in the API doc. The reason to have a renderType is the user may apply different styles for an unfinished polygon (of which geojson type is lineString). I will update the doc.


> your features have prop id - not sure why the library isn't using the geojson standard feature.id attribute instead?

I am not aware of `feature.id` is a standard GeoJson spec and the original intention to use `id` is to provide a way to track the features (internally), however after the refactor, I am deprecating this `id` in the newer version, instead using `selectedFeatureIndex`.

**Comment by xintongxia** [comment]
@macobo 

published 0.16.1 should fix the issue `react-map-gl-draw: state is not initialized properly from props on mount in ModeHandler`.

**Comment by zoenberger** [comment]
Hi @macobo I wanted to see if you had any luck editing features that originate outside of react-map-gl-draw? I'm loading data via redux into a features array and giving that to the Editor. But I cannot move/edit those features. (I can, however, add vertices to a polygon.)

I can also draw a new polygon and add it to features array, but still no moving/editing.  Here is a minimal repo (using hardcoded polygon features). 

@xintongxia I love the work you've done...if I can figure out how to get everything working when I provide the features array, I'll be all set! Thanks!

**Comment by xintongxia** [comment]
I created a [sandbox](https://codesandbox.io/s/react-map-gl-draw-with-initial-features-m0e97?file=/public/index.html) with passing in initial features.
