### ISSUE TITLE
Remove event handling hack

### ISSUE THREAD

**Issue by Pessimistress** [uber/nebula.gl#276]
The `EditableLayer` used to bind/unbind event handlers on every update:

https://github.com/uber/nebula.gl/blob/4ffcd762820b234d0bc5b5db72d173004782c658/src/lib/layers/editable-layer.js#L91

Because `this` i.e. the layer instance may change over time.

A better solution to this problem is to use the `layer.getCurrentLayer()` method:

```js
canvas.addEventListener(
  'pointermove',
  event => {
    const layer = this.getCurrentLayer(); // returns the latest layer instance
    this._onPointerMove.call(layer, event);
  }
);
```

This should work with registering/unregistering events only once on initialization/finalization.

#### To Do List 
  - [x] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by supersonicclay** [comment]
Can we go one step further with this and refactor to use mjolnir?

**Comment by Pessimistress** [comment]
> Can we go one step further with this and refactor to use mjolnir?

We can add the `EventManager` to the layer context. That should unblock you?
