### ISSUE TITLE
Inconsistent Cursor

### ISSUE THREAD

**Issue by supersonicclay** [uber/nebula.gl#28]
Sometimes the mouse cursor is a hand, sometimes vertical resize arrows. Expected to be consistent. Even better if it changes to reflect what the cursor is over (base map vs. feature vs. edit handle of a feature).

**Comment by georgios-uber** [comment]
I think the base map is interfering with the cursor.

**Comment by hamidrz021** [comment]
Hi
can you make me an example or codesandbox that show how to change the cursor style to crosshair when wanting to draw a polygon?
thanks

**Comment by supersonicclay** [comment]
https://codesandbox.io/s/hello-world-nebulagl-csvsm should demonstrate it

**Comment by garretteklof** [comment]
What's the recommended way to handle cursor updating with `react-map-gl-draw`? I've managed to switch to 'crosshair' when drawing via `getCursor` manipulation, but unsure how to give a 'pointer' during the hover state as that's not seemingly React.
