### ISSUE TITLE
getColor is deprecated in ScatterplotLayer

### ISSUE THREAD

**Issue by romaxa** [uber/nebula.gl#281]
#### Describe the bug
use of deprecated deck layer properties
#### Actual Result
see deprecated use warning
#### Expected Result
no deprecated use warning
#### Reproduce Steps
Create JunctionScatterplotLayer

Code 
https://github.com/uber/nebula.gl/blob/master/modules/layers/src/layers/junction-scatterplot-layer.js#L24

**Comment by supersonicclay** [comment]
@romaxa can this be closed now?

**Comment by georgios-uber** [comment]
Fixed. Thanks @romaxa
