### ISSUE TITLE
Support nebula.gl for drawing polygon using @deck.gl/google-maps

### ISSUE THREAD

**Issue by snehabhapkar** [uber/nebula.gl#286]
**Feature request**

Nebula works perfect with deck.gl or react-map-gl. 
However it doesn't work with @deck.gl/google-maps

**Comment by Pessimistress** [comment]
Google Maps does not allow third-party overlays to receive pointer events. There's not much we can do there. :(

**Comment by snehabhapkar** [comment]
Thank you! Closing the issue :)

**Comment by wazirsoft** [comment]
> Google Maps does not allow third-party overlays to receive pointer events. There's not much we can do there. :(

Is there any reference to this policy from Google? Like a link where I can read it from? Thanks

**Comment by Pessimistress** [comment]
@wazirsoft See this https://github.com/uber/deck.gl/issues/3354#issuecomment-512058596 from Google:

> There is a fairly strong assumption within Maps API that it manages mouse events itself.

**Comment by wazirsoft** [comment]
@Pessimistress so it means we would have to use Google Maps API to do the editing instead of using Nebula.gl?
