### ISSUE TITLE
Ability to draw circle with react-map-gl-draw

### ISSUE THREAD

**Issue by intelcoder** [uber/nebula.gl#293]
#### Feature request
I would like to draw circle with react-map-gl-draw but it does not have api for circle.

I saw drawing circle for the nebula.gl was done last year. 
Is there anyway or reference to draw circle until drawing circle feature is done?

**Comment by intelcoder** [comment]
I tried to add draw circle mode. Could you guys check this?
https://github.com/intelcoder/tmp-react-map-gl-draw/pull/1

**Comment by aconital** [comment]
Can that be accepted as a pull request? @georgios-uber @intelcoder

**Comment by supersonicclay** [comment]
What we'd like to do actually is refactor `react-map-gl-draw` to use `@nebula.gl/edit-modes` module like the deck.gl version does. Then it would gain all the edit modes that the deck.gl version of nebula supports (including circles, elipses, rectangles, polygons, points, lines, translating, scaling, rotating, etc).

**Comment by intelcoder** [comment]
@supersonicclay I am guessing that would take a while and make the library heavier. 
we cannot utilize the current library until refactoring is done? 

[circle-draw-mode](https://github.com/intelcoder/tmp-react-map-gl-draw/pull/1/files#diff-c23f75a4c9e0eaf6b7539462779c0673)

**Comment by howdyhyber** [comment]
+1 to this feature.

**Comment by xintongxia** [comment]
@intelcoder would you like to contribute and open a pull request?

**Comment by rubenmoya** [comment]
Hello! I need this for a project I'm working on, is there something I can do to help move this forward?

**Comment by Covicake** [comment]
> Hello! I need this for a project I'm working on, is there something I can do to help move this forward?

I'm also willing to help to move this forward

**Comment by xintongxia** [comment]
@rubenmoya @Covicake 
Drawing circle is available in v0.18.3. Note: Aftering finish drawing a circle, editing/modifying the completed circle is currently not supported.
