### ISSUE TITLE
When initial features are provided to editor. Edit stop working(react-map-gl-draw)

### ISSUE THREAD

**Issue by intelcoder** [uber/nebula.gl#295]
#### Describe the bug
If I manage features with state, edit functionality stop working such as moving, dragging vertex.

#### Actual Result
initial feature can have new vertex and can be selected but it cannot be moved or updated

#### Expected Result
Able to update feature such as position and shape

#### Reproduce Steps
pass features to Editor component and try to modify feature on the map

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by aconital** [comment]
I'm having the same issue. Once you pass a polygon to Editor (Not created with the draw tool), you can't edit it.

**Comment by intelcoder** [comment]
mode-handler.js
_onEdit
```
 case EDIT_TYPE.MOVE_POSITION:
        // intermediate feature, do not need forward to application
        // only need update editor internal state
        this._onUpdate(editAction, true);
```
Is there any reason why you guys disabled user feed features by passing true to the _onUpdate function ?
Can we do something like this ?

`this._onUpdate(editAction, !Boolean(this.props.features));`

**Comment by zoenberger** [comment]
I'm still looking for a solution to this same issue. If I provide a features array to the Editor, I am unable to edit those features. I can select a feature (and the vertices highlight) but I cannot move feature, add vertices, or edit vertices.

**Comment by georgios-uber** [comment]
In order for anything to move you need to listen to updates and pass the new features back to the EditableGeojsonLayer.

**Comment by zoenberger** [comment]
Well, I guess that makes sense. I had an onUpdate function supplied to Editor, but I wasn't handling the "addPosition" event, for example. I did that, and now I can add vertices on a feature.

I think I just don't understand how to handle all the events. For example, I can select my feature, but how do move it? 

Perhaps someone has an example of an implementation that uses a state-managed features array that shows how to handle all the things one might do, such as add a feature, move a feature, add a position, move a position, etc.  The existing example works great for Editor-managed features. 

I have a barebones repo here: https://github.com/zoenberger/React-Map-Draw-GL---Polygon-Test

It loads one polygon into the state-managed features array. Adding a vertices to the polygon works. If anyone has tips on moving/editing the polygon, that would be super awesome.

**Comment by supersonicclay** [comment]
nebula.gl is very unopinionated because so many applications have very specialized needs. nebula.gl exposes very specific modes for accomplishing specific tasks. It is intended for a consuming application to switch modes as necessary (e.g. by key presses, pressing buttons on a toolbar, selecting a feature, etc).

To move a whole feature/shape, you want the `TranslateMode`. For moving individual vertexes of a shape, you want `ModifyMode`.

Probably the best way to learn the various modes nebula.gl supports is by playing with the demo app [here](https://nebula.gl/geojson-editor/).

**Comment by zoenberger** [comment]
Thanks @supersonicclay 

I guess maybe I misunderstood the scope of the react-map-gl-draw module. I am having same experience as person who posted this issue: If you allow the Editor to manage the features array, then the library does all the work for you regarding editing/moving features. This requires no direct usage of nebula or deck. 

But it sounds like if I want to manage the collection of features myself (for example, loading a features set from a data source), then the library can no longer help me with editing/moving features.

**Comment by supersonicclay** [comment]
Ah, I see. I missed that you are using `react-map-gl-draw`. Have you tried using the deck.gl based [EditableGeoJsonLayer](https://github.com/uber/nebula.gl/blob/master/docs/api-reference/layers/editable-geojson-layer.md)? At this time, it has more functionality and is better tested.

**Comment by zoenberger** [comment]
I have a very limited use case: draw a few polygons and get the coordinates to my database. With the module, this was extremely fast and easy. I was hoping I was going to get lucky and life would be easy.

I started looking at EditableGeoJsonLayer as was mentioned above. It appears I'll have to dig-in to the mentioned nebular tutorials and go that route.

**Comment by intelcoder** [comment]
I mentioned before 
currently, library passes true to the _onUpdate like below 
`
// intermediate feature, do not need forward to application
// only need update editor internal state
this._onUpdate(editAction, true);
`

Is there any reason why we can pass dynamic value to the second args? 

because below code enables edit mode

`this._onUpdate(editAction, !Boolean(this.props.features));`

**Comment by supersonicclay** [comment]
The simple use case for drawing polygons should be fairly easy with nebula.gl. Here's some sample code:

```js
import DeckGL from 'deck.gl';
import { EditableGeoJsonLayer, DrawPolygonMode } from 'nebula.gl';

const myFeatureCollection = {
  type: 'FeatureCollection',
  features: [
    /* insert features here */
  ]
};

const selectedFeatureIndexes = [];

class App extends React.Component {
  state = {
    data: myFeatureCollection
  };

  render() {
    const layer = new EditableGeoJsonLayer({
      id: 'geojson-layer',
      data: this.state.data,
      mode: DrawPolygonMode,
      selectedFeatureIndexes,

      onEdit: ({ updatedData }) => {
        this.setState({
          data: updatedData,
        });
      }
    });

    return <DeckGL {...this.props.viewport} layers={[layer]} />;
  }
}
```

You can also see it working in a codesandbox here: https://codesandbox.io/s/hello-world-nebulagl-csvsm. Just make sure you put in your own mapbox token.

**Comment by intelcoder** [comment]
@supersonicclay Thanks for the code. 
However, I prefer not to use deck.gl only for one drawing feature because of bundle size.
My suggestion is not acceptable at the moment?

**Comment by KatherineGraham2019** [comment]
I am curious about intelcoder's suggestion as well. I have a fairly simple use case with react-mapbox-gl and wanted to use react-map-gl-draw to manage a polygon I have added to the map via managing my own features, why can't that be editable? I don't understand what the point is in making that ineditable?

**Comment by xintongxia** [comment]
@intelcoder sorry for the late response. this is fixed in v0.18.4

Check this [sandbox example](https://codesandbox.io/s/react-map-gl-draw-with-initial-features-m0e97?file=/src/App.js)

**Comment by zoenberger** [comment]
I've updated to v0.18.4 and can now provide my own array of features as demonstrated in sandbox example.  Many thanks!

**Comment by DonovanCharpin** [comment]
I have the same issue with the last version 0.22.3, is there something else to do? The sandbox example above works great until you update the version.
