### ISSUE TITLE
A flag to switch to standard draw mode

### ISSUE THREAD

**Issue by hip1310** [uber/nebula.gl#301]
#### Feature request
Is it possible to introduce a flag for dragAndDraw, which is when true enable to draw rectange/polygon on mousedown and on releasing mouseclick (onmouseup) it would close the rectangle and fire onUpdate() method with the selected coords. I was looking at the code, and seems like it's possible. Just need a little guidance so that I can go ahead and create a pull request with that feature.

This feature will be helpful as it will introduce standard flow of drawing rectangle (mouseclick and drag which mouse click down and on release close drawing)

Thanks for this amazing package.

**Comment by claykohut** [comment]
Also interested in this

**Comment by georgios-uber** [comment]
You can extend the current handler and implement your own.
Feel free to open a PR if you have made this work and want to share.
