### ISSUE TITLE
Ability to add elevation/altitude in linestring ?

### ISSUE THREAD

**Issue by anujsinghwd** [uber/nebula.gl#302]
- Feature
- Shown in the below picture
![ele](https://user-images.githubusercontent.com/24680004/69721348-a909f980-113a-11ea-9fed-a5358cd8b0b8.jpg)

**Comment by georgios-uber** [comment]
Yes, just add a third number in the coord array (as defined by geojson standard).

**Comment by georgios-uber** [comment]
Solved.
