### ISSUE TITLE
react-map-gl-draw geometry is updated with an obvious delay when viewport changes.

### ISSUE THREAD

**Issue by zhenyanghua** [uber/nebula.gl#306]
#### Describe the bug
After drawing a feature with this `Editor` component, one can see an obvious delay from the geometry that is drawn to updated to the correct position.

#### Actual Result
The geometry is not updated in time which produces an obvious delay when viewport changes.

#### Expected Result
The geometry should be updated as the viewport changes just like the any other layers.

#### Reproduce Steps

1. Go to [https://uber.github.io/react-map-gl/#/Examples/draw-polygon](https://uber.github.io/react-map-gl/#/Examples/draw-polygon)
2. Click the draw button to draw a polygon
3. After completing a polygon, zoom in or zoom out using mouse wheel without moving the mouse. 
4. One will find the polygon is stuck in an intermediate outdated location
5. Move the mouse
6. One will find the polygon finally is updated to the correct location.

#### Screenshots
After drawing the polygon, one will find the polygon is aligned with the field grid:
![image](https://user-images.githubusercontent.com/6165894/71104071-3912f000-2189-11ea-8ebf-381dadbc200a.png)
Scroll the mouse wheel and not moving mouse, one will find the polygon is stuck in an intermediate outdated location:
![image](https://user-images.githubusercontent.com/6165894/71104183-69f32500-2189-11ea-96ed-f7fbd2cf335c.png)
Not until the mouse is moved, will the polygon be ever updated with the correct location.

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by xintongxia** [comment]
Thanks for reporting. I'll look into it shortly.

**Comment by zhenyanghua** [comment]
In our case we created a viewport context to observe the viewport change events. When use use this context in the parent component that renders the `Editor` component, the geometry will not be stuck, but still updated with a delay. 

Wonder if there is a throttle behavior added the viewport change event on the map from this tool which causes the delay of rendering.

**Comment by petzel** [comment]
Also having this issue. After zooming in/out, polygons (or other shapes) will not update until the mouse is moved.

**Comment by xintongxia** [comment]
Should be fixed in v0.17.2

**Comment by zhenyanghua** [comment]
It's resolved with v0.17.2.
