### ISSUE TITLE
Pure JS/Other Framework Examples?

### ISSUE THREAD

**Issue by jfuehner** [uber/nebula.gl#307]
Hi! I'm just starting to dive into the deck.gl ecosystem. With that said, I was curious if there are plans provide examples for using nebula.gl with other frameworks beyond React? At the very least it would be great if you could add examples using nebula with pure javascript similar to what deck.gl has done.

Thank!

**Comment by georgios-uber** [comment]
You can use Editable Geojson Layer with or without react. Overlays are currently react-only.

**Comment by jfuehner** [comment]
@georgios-uber Safe to assume I could use the Editable Geojson Layer to implement a zoom to extent feature similar to how mapbox does?

**Comment by georgios-uber** [comment]
Yes, should work.

**Comment by georgios-uber** [comment]
Need any more help?

**Comment by jfuehner** [comment]
@georgios-uber Think I'm good for the moment. I'm sure I'll have additional questions though as I work through things... ;-)

**Comment by georgios-uber** [comment]
Great.
