### ISSUE TITLE
selection from null to index 0 doesn't trigger any selection aware member functions

### ISSUE THREAD

**Issue by matthrice** [uber/nebula.gl#31]
Selection event from `selectedFeatureIndex = null` to `selectedFeatureIndex = 0` doesn’t seem to trigger any of the selection aware member functions. Same for the reverse, `0` to `null`. 

Can be seen in the deck example by going to `view` mode, deselecting and incrementing the selection. The point doesn't highlight.

**Comment by supersonicclay** [comment]
This might be a deck.gl issue. I'd be curious if this could be reproduced with `GeoJsonLayer` or even `ScatterplotLayer`.

**Comment by supersonicclay** [comment]
Indeed, deck.gl issue:
https://github.com/uber/deck.gl/issues/2068
