### ISSUE TITLE
react-map-gl-draw methods

### ISSUE THREAD

**Issue by Robert-OP** [uber/nebula.gl#315]
Hello guys,

Great job with the library, appreciate the effort! 

1\ How can I use react-map-gl-draw methods?

I cannot seem to figure out how to use the methods. I am interested in the deleteFeatures method.

Cheers

**Comment by xintongxia** [comment]
@Robert-OP 
Here are some examples you can check


https://github.com/uber/nebula.gl/tree/master/examples/react-map-gl-draw
https://github.com/uber/react-map-gl/tree/master/examples/draw-polygon

**Comment by Robert-OP** [comment]
Thank you @xintongxia - sorry for the late response, I will check it out and let you know how it goes and close this issue :)
