### ISSUE TITLE
react-map-gl-draw double click in EditorModes.DRAW_POLYGON does not finalize the polygon

### ISSUE THREAD

**Issue by vmary2014** [uber/nebula.gl#330]
Hi
Fabulous library thanks for the efforts going into this, really appreciate it.
I think there might be an issue when the Editor is set to **EditorModes.DRAW_POLYGON**
When I draw a polygon on the map and double click I was expecting it to finalize the polygon, as per the MapBox example [here](https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-draw/).
However it doesn't and instead you are forced to close the polygon by clicking last on the first point/handle you drew on the map.
Is there a way to get it to do that ? I could not find any doc about this.
Thanks.
Vincent
#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by xintongxia** [comment]
@vmary2014 current `react-map-gl-draw` doesn't capture the double click event. I'll evaluate the complexity of this feature.

**Comment by christensenmichael0** [comment]
@vmary2014 @xintongxia will this update also apply when terminating a polyline with a double click?

**Comment by xintongxia** [comment]
avmary2014 @christensenmichael0 double click to finalize a polygon is added in  v0.18.3

**Comment by vmary2014** [comment]
> avmary2014 @christensenmichael0 double click to finalize a polygon is added in v0.18.3

Thanks so much for doing this ! Much appreciated.
