### ISSUE TITLE
Double click to finish drawing a line

### ISSUE THREAD

**Issue by rmGuarachi** [uber/nebula.gl#343]
Is there a way to double click on the last point to finish drawing a line? or What would be the best way to do this?

Thank you

**Comment by supersonicclay** [comment]
Are you using `EditableGeoJsonLayer` or `react-map-gl-draw`?

**Comment by rmGuarachi** [comment]
I am using EditableGeoJsonLayer.

**Comment by omasback** [comment]
I'm using `react-map-gl-draw` and it would be nice to have this behavior there too.

**Comment by xintongxia** [comment]
@omasback this feature is included `v0.18.3`
