### ISSUE TITLE
When draw mode is in read only,  drawn shape moves as map panning and move back

### ISSUE THREAD

**Issue by intelcoder** [uber/nebula.gl#346]
#### Actual Result
Shape moves with map on panning and move back to original position
#### Expected Result
Shape stays same place as user panning

#### Screenshots
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/10482739/76099212-cac81780-5f98-11ea-99fc-afb4a3661a75.gif)

**Comment by georgios-uber** [comment]
Is this EditableGeoJson Layer or react-map-gl-draw?

**Comment by intelcoder** [comment]
Sorry. It is  react-map-gl-draw

**Comment by xintongxia** [comment]
should be fixed in v0.18.3. Feel free to reopen if you still see this isse.
