### ISSUE TITLE
EditableGeoJson Custom Modes

### ISSUE THREAD

**Issue by baxter1707** [uber/nebula.gl#350]
Apologies if this is asked in the incorrect section. 

Returning to this library after working on 0.15.0. A lot of great work has been done! 

Question:
Is it still possible to utilize CustomModeHandlers, or has this been completely removed?

**Comment by supersonicclay** [comment]
Yes, you can still build custom modes. However, the API changed a fair bit to be more stateless. We have it documented in the [changelog](https://github.com/uber/nebula.gl/blob/master/CHANGELOG.md) under version 0.16.0.

**Comment by baxter1707** [comment]
@supersonicclay Thank you for the quick answer and the link to the docs! Big help!

**Comment by supersonicclay** [comment]
You bet! And if you're mode is general purpose you can also suggest it be added to nebula (or enhance an existing mode) through an issue or PR.

**Comment by baxter1707** [comment]
@supersonicclay Ill keep that in mind! I had another question. Im trying to replace ModeHandler with GeoJsonEditMode as the change log suggests. Where should I be importing GeoJsonEditMode from? When importing from the nebula.gl package it comes back as undefined.

**Comment by kikonejacob** [comment]
@supersonicclay  I seem to have the same issue.
GeoJsonEditMode is exported as a flow type which is not usable if you are not using flow types

 BaseGeoJsonEditMode could be the class I'm looking for to create a custom handler but it is not exported.

**Comment by supersonicclay** [comment]
Good catch. Published 0.17.5. `GeoJsonEditMode` is the one you want now.
