### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by kikonejacob** [uber/nebula.gl#354]
#### Feature request
Is there any plan to move this repo to typescript?

#### To Do List 
  - [ ] Add label and assign to milestone
  - [x] Coding
  - [ ] Doc update
  - [ ] Test

**Comment by supersonicclay** [comment]
Currently we are using Flow internally in the repository. We'd like to support TypeScript in the future, but we have no current plans for it.

**Comment by kikonejacob** [comment]
Thank you for your quick answer. It will be nice to have typescript support as more app are using typescript. I think it will be pretty similar to flow.

**Comment by kikonejacob** [comment]
Will you take a Pull request to does the conversion?
I feel like you guys have already defined a lot of types and it will be really useful to move to use a tool with a wider community.

**Comment by ibgreen** [comment]
Just as a side note we are working on adding typescript support to a number of the other frameworks in the vis.gl framework suite.

The strategy there is to keep the code as pure JavaScript and add types in `d.ts` files. E.g. 

- https://github.com/uber-web/math.gl/pull/129
- https://github.com/uber-web/loaders.gl/pull/670

Obviously nebula.gl already uses flow so this may not work for nebula (at least I assume trying to "lint" the code with `tsc` compiler wouldn't work). But that is the direction the rest of the suite is going right now.

**Comment by kikonejacob** [comment]
Thank you @ibgreen,
I understand that there is an internal discussion about types and I understand that people may have different opinions about types.
I really like this project and would like to see it in better tooling.

**Is there any reason to keep types separated from javascript?**  
Will this mean double maintenance of js file and typescript files?
 Would it be better to use https://babeljs.io/docs/en/babel-preset-typescript and generate the types directly and let typescript generate .js and d.ts?
I think typescript is not that different from js except the types and .ts file extension.

I think the only tradeoff when moving to typescript for nebula will be to rename .js to .ts and fix some small type difference between flow and typescript.

I think the advantage of type for a developer is to know what is wrong as I type code in my editor instead of running a CLI tool to see if my types are right.  Typescript definitely does a better job at it.
Thank you all for a quick answer.

**Comment by kikonejacob** [comment]
@supersonicclay  @ibgreen Do you have an ETA for typescript support?

**Comment by ibgreen** [comment]
@kikonejacob  nebula.gl is on an independent track from the other vis.gl frameworks, so maintainers would need to make the decision to add typescript support, and @supersonicclay says above that there are no current plans for it.

If you have an interest in contributing typescript `.d.ts` definition files, I am happy to review PRs and help coordinate landing them.

**Comment by ibgreen** [comment]
> Do you have an ETA for typescript support?

For the other frameworks typescript is tentatively planned to be synched with deck.gl 8.2 - which does not yet have an official release date, but I would guess we will see a release within 2 months.

**Comment by kikonejacob** [comment]
Thank you for your prompt answer. Glad to know the other frameworks will be supporting typescript.
Generating .d.ts would be nice but maintaining them would be a little difficult and it will hard to catch up with type definition from flow-types since we will always need to catch up with flow types. I would have been in favor of this approach if this project was in `raw javascript` only. 

**I would be more than happy to contribute if there is going to be a switch from flow-types to typescript**.    Flow-type project is dying to typescript and it will be better to switch.
That being said, I understand that the maintainers are not interested at the moment.

**Comment by ibgreen** [comment]
> it will hard to keep type definitions up to date since we will always need to catch up with flow types

Keeping the types up-to-date is not hard and would be handled by maintainers, not by you. This is what we will be doing for the other frameworks.

> I would be more than happy to contribute if there is going to be a switch from flow-types to typescript. Flow-type project is dying to typescript and it will be better to switch.

@kikonejacob I think you are missing a big opportunity to make a change here :) By adding typescript types, you would help the maintainers take the first step towards replacing flow. 

As you already said, typescript is gaining traction over flow, and also there are tools to use typescript types in flow. 

Once you have added typescript definition files, it will be much easier for users to start experimenting with using ts types instead of flow types.

**Comment by supersonicclay** [comment]
I would love to see nebula use typescript inside and out. It may just as easy to convert all the flow stuff to typescript as it would be to add `.d.ts` files after-the-fact. We don't have the flow typings exported outside of nebula. So, nebula.gl is not terribly tied to flow at this point.

**Comment by supersonicclay** [comment]
I started a hack and slash conversion from flow to typescript. I don't know how much it'll take to make it work all the way.

@kikonejacob: if you can help us move this effort forward, that'd be great!

**Comment by supersonicclay** [comment]
@georgios-uber @xintongxia I'm curious your input on this

**Comment by kikonejacob** [comment]
@supersonicclay  @ibgreen  I create another PR #377 where I completed the migration of modules packages to typescript. I want to start from scratch so I can take advantage of automated tools.
Please review and let me know.
My apologies, this is my first time committing to a public open-source project.
