### ISSUE TITLE
react-map-gl-draw drag issue triggers finishMovePosition and clear features

### ISSUE THREAD

**Issue by avdeyev** [uber/nebula.gl#355]
#### Describe the bug

v.0.17.3

Issue happens when you have several features and tries to drag one onto another without preselection in mode.EDITOR

#### Actual Result

All features are disappeared. Console triggers onUpdate with: editType:"finishMovePosition", data: "null"

#### Expected Result

Nothing should happen I guess

#### Reproduce Steps

1. Create 2 polygons
2. Switch to mode.EDITOR and clear selection
3. Try to drag 1 feature onto another

#### Screenshots

![draw issue](https://user-images.githubusercontent.com/3809273/77042901-87749c80-69cd-11ea-9aad-b843875f061b.gif)

**Comment by xintongxia** [comment]
Could you try the new version v0.18.3 which fixes this issue. Thank you.

Here is the [playground](http://xintong-xia.com/react-map-gl-draw/) with the most recent version.
