### ISSUE TITLE
react-map-gl-draw doesn't handle GeoJSON Point feature

### ISSUE THREAD

**Issue by yurivangeffen** [uber/nebula.gl#368]
#### Describe the bug
Point is not proper GeoJSON.
#### Actual Result
When using point as defined in GeoJSON like
```{
    "type": "Point", 
    "coordinates": [30, 10]
}
```
as a feature, a TypeError occurs deep inside WebMercatorViewport:
```
TypeError: Invalid attempt to destructure non-iterable instance
```

#### Expected Result
To have the package use the GeoJSON standard as advertised in the README. The package does work when using `[[30, 10]]` as coordinates.
#### Reproduce Steps
1. Create a map view.
2. Add a feature collection to it.
3. Add a feature like the following to the feature collection:
```{
   type: "Feature",
   geometry: {
     type: 'Point',
     coordinates: [30, 10]
   },

   properties: {
     renderType: 'Point',
     type: 'Start'
   }
 }
```

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by xintongxia** [comment]
Should be fixed in v0.18.4

[sandbox example](https://codesandbox.io/s/react-map-gl-draw-with-initial-features-m0e97?file=/src/App.js)
