### ISSUE TITLE
Block & Lasso select

### ISSUE THREAD

**Issue by supersonicclay** [uber/nebula.gl#37]
Add ability to select one or more features by drawing a rectangle

**Comment by kargeor** [comment]
I have that ability already but maybe we need to refactor.

**Comment by kargeor** [comment]
Check src/lib/deck-renderer/deck-drawer.js

**Comment by georgios-uber** [comment]
https://github.com/uber/nebula.gl/pull/128

**Comment by supersonicclay** [comment]
👍
