### ISSUE TITLE
The examples don't work

### ISSUE THREAD

**Issue by omasback** [uber/nebula.gl#378]
I've tried advanced, editor and react-map-gl-draw examples and none of them work. This isn't an urgent bug as it's not blocking me. Just letting you know.

**Comment by austintang** [comment]
Can you elaborate on what you mean by none of these examples work? What are the steps to reproduce the issues you're encountering?

**Comment by omasback** [comment]
I'm sorry I think i was trying to run them on a pull request branch/fork. They work on master. My bad, disregard!
