### ISSUE TITLE
Combine Editing Mode: Move+ Rotate+ Scale

### ISSUE THREAD

**Issue by kikonejacob** [uber/nebula.gl#380]
#### Feature request
Can we combine Move+ Rotate+ Scale when editing a geometry?
 It will be nice to be able to do all that without clicking a button. It will feel more natural.
Thank you
#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Doc update
  - [ ] Test

**Comment by supersonicclay** [comment]
Have you seen the new `TransformMode`? It hasn't been deployed to the website yet, but it is on master and published to npm.

[docs](https://github.com/uber/nebula.gl/blob/master/docs/api-reference/modes/overview.md#transformmode)
Original PR: #340

**Comment by kikonejacob** [comment]
Cool Thanks. This issue can be closed
