### ISSUE TITLE
Prettier integration?

### ISSUE THREAD

**Issue by wuweiweiwu** [uber/nebula.gl#383]
#### Feature request

- prettier integration (precommit hook) since this project already use the prettier eslint defaults
- formatting is quite inconsistent across the codebase 
- happy to volunteer some time to knock this out

#### Background 

- better devX

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Doc update
  - [ ] Test

**Comment by xintongxia** [comment]
@wuweiweiwu Feel free to help improve the formatting! Thank you!

**Comment by wuweiweiwu** [comment]
@xintongxia sounds good!
