### ISSUE TITLE
Double-click does not complete polygon or line string

### ISSUE THREAD

**Issue by kikonejacob** [uber/nebula.gl#387]
#### Describe the bug
When drawing a line or polygon, double-clicking should complete the polygon or line. 
#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

![Apr-16-2020 08-47-27](https://user-images.githubusercontent.com/3852574/79463816-ed4d4780-7fbe-11ea-9efe-3b976fecafec.gif)

**Comment by supersonicclay** [comment]
We recently updated this mode. It is available in the latest version on npm, but we just haven't updated the website yet.

You can see an example here:
https://codesandbox.io/s/draw-linestring-df9tc

![draw-linestring](https://user-images.githubusercontent.com/469582/79530471-9e3dfb80-802c-11ea-86db-9196d9b475e3.gif)

**Comment by kikonejacob** [comment]
I guess I was expecting the draw to exit when I double click. same for polygon draw

**Comment by supersonicclay** [comment]
Good find. That used to work, but it seems that functionality broke. If you click and move the mouse slightly, then you can click again and it'll complete the line.
