### ISSUE TITLE
Line overlaps filled shape

### ISSUE THREAD

**Issue by kikonejacob** [uber/nebula.gl#388]
#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test
![image](https://user-images.githubusercontent.com/3852574/79513154-c3207780-8008-11ea-9233-a6d43cb24149.png)

**Comment by supersonicclay** [comment]
nebula.gl uses [deck.gl](https://github.com/visgl/deck.gl) for rendering. You may want to look into the web gl blending options, or log the issue against deck.gl's repo instead of here.

You can use this code sandbox for repro:
https://github.com/visgl/deck.gl
