### ISSUE TITLE
Imported react-map-gl-draw example in next.js

### ISSUE THREAD

**Issue by chiho13** [uber/nebula.gl#394]
I've imported the example into my next.js react project. I do not understand why it's not working. There is no error logging. It's just not drawing the polygons and rectangles onto the map

**Comment by xintongxia** [comment]
@chiho13 

It is easier to develop and debug with a map, so first do you see the map? If not, could you apply a mapbox token and provided in the app?

Also make sure the drawing part takes the full size if your screen.

**Comment by chiho13** [comment]
The map is showing, but i am unable to draw a rectangle.

**Comment by xintongxia** [comment]
@chiho13 

Could you be more specific about the issues? 
- Does the drawing editor (a `<div>` element with id `editor`) actually render in your app?
- Do you see any errors?
- Note: `onSelect` has to be provided. Will have a PR to fix this.

Here is a [sandbox example](https://codesandbox.io/s/react-map-gl-draw-example-5n97w?file=/src/app.js.

**Comment by chiho13** [comment]
Yes, the element with id editor is rendered.
I don’t see any errors.
onSelect is already provided.

i copied the exact example into my next.js app. I used my own map access
token. Viewports is working fine. Could it be a issue with turf?

**Comment by chiho13** [comment]
Hey i got it working. It seems it was an issue with turf’s mjs files.
Thanks for responding so quickly

**Comment by ekimcem** [comment]
@chiho13 , can you please explain how you solved it ? I also have problem with it.
