### ISSUE TITLE
react-map-gl-draw: navigating around the map by dragging the mouse 

### ISSUE THREAD

**Issue by kludcev** [uber/nebula.gl#397]
When I am trying to move around the map by mouse drag nothing happens.
Is it a bug? 
Is there any solution or workaround to enable that feature?

codesandbox example: https://codesandbox.io/s/dreamy-chebyshev-k70fo

**Comment by alamribah** [comment]
Yes, it's a bug. The draw package from urbica and  react-mapbox-gl-draw doesn't have this issue.
I tried the example provided in uber/nebula.gl/examples/react-map-gl-draw and I can confirm that drag doesn't work. I tried fixing it myself but I, unfortunately, I couldn't find the error.

**Comment by xintongxia** [comment]
@kludcev `react-map-gl-draw` currently blocked map interaction while drawing. However it might be possible to allow interaction while there is no selected geometry. I'll investigate the possibility.

**Comment by xintongxia** [comment]
should be fixed in `v0.18.3`

**Comment by joaogn** [comment]
I'm using 0.22.3 and not working.
