### ISSUE TITLE
Hit or Miss Selection Layer

### ISSUE THREAD

**Issue by btbritz** [uber/nebula.gl#401]
So here's my scenario:  I couldn't get the **SelectionLayer** working for some reason, even though i double and tripe checked the documentation, so I left it overnight and came back to it working just fine.

I played around with it for a bit and decided to put in an `If button has been pressed add the SelectionLayer to my deck and redraw`. Doesn't seem to work again...ok. I remove the if statement, so now it's exactly the way it was when it worked a few moments ago, but as you might have guessed, doesn't work.

What the heck am I doing wrong? Here's my code:

```
import { SelectionLayer } from 'nebula.gl'
...
_deck.gl and other imports_
...

layers.push(new ScatterplotLayer({
    id: `patent-scatter`,
    data: [this.whateverData]
    ...
   _other deck.gl standard options_ 
}))

layers.push(new SelectionLayer({
    id: 'selection',
    selectionType: 'SELECTIONTYPE.RECTANGLE',
    onSelect: ({ pickingInfos }) => {
        console.log(pickingInfos)
    },
    layerIds: ['patent-scatter'],
    getTentativeFillColor: () => [255, 0, 255, 100],
    getTentativeLineColor: () => [0, 0, 255, 255],
    getTentativeLineDashArray: () => [0, 0],
    lineWidthMinPixels: 1
}))
```

Thanks in advance for the help!

**Comment by btbritz** [comment]
Any help on this would be greatly appreciated!

Thanks

**Comment by xintongxia** [comment]
@btbritz 

For your deck.gl layers, you need enable picking

```
new ScatterplotLayer({
    id: `patent-scatter`,
    data: [this.whateverData]
    pickable: true,
    ...
})
```


For nebula.gl SelectionLayer, you need pass SelectionType 'rectangle' or 'polygon', sorry for the misleading documentation.

**Comment by btbritz** [comment]
Ugh I'm not sure why I didn't try that. Thank you @xintongxia , works as expected.
