### ISSUE TITLE
Keyboard shortcut to end and cancel draw

### ISSUE THREAD

**Issue by kikonejacob** [uber/nebula.gl#402]
#### Feature request
Can we add the following shortcuts ?: 
- ESC to cancel the draw
- ENTER to end draw 
#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Doc update
  - [ ] Test

**Comment by georgios-uber** [comment]
Sure. BTW, it would be really nice if someone opened a PR that does that 😄

**Comment by supersonicclay** [comment]
Currently nebula doesn't handle keyboard events. It could be added without too much issue, but it isn't a priority for us at the moment.

For now, you can add a key event handler in your application and force nebula to cancel drawing by switching modes and switching back. That'll force nebula to clear its tentative features (e.g. an incomplete polygon). However, if you're looking to commit what's been drawn so far when drawing a LineString, you may have to make that change in nebula itself.
