### ISSUE TITLE
Request to export utils in index.ts

### ISSUE THREAD

**Issue by balaram4cyngn** [uber/nebula.gl#421]
#### Feature request
Kindly export utils for downstream use in index.ts the way types and geojson_types are exported.

#### Background 
https://github.com/uber/nebula.gl/blob/master/modules/edit-modes/src/index.ts
I am trying to play with some of the edit modes and it'll be great if the utils can be exported too.

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Doc update
  - [ ] Test

**Comment by supersonicclay** [comment]
We'd welcome a pull request for this.
