### ISSUE TITLE
Adding and editing polygons with geojson data

### ISSUE THREAD

**Issue by hamidrz021** [uber/nebula.gl#428]
Hello
I receive a geojson data from backend and i want to draw and show polygon or points on map with that geojson data
then edit this shapes and send it to backend
how can i do this?
do I have use nebula.gl?
I'm using react-map-gl-draw now, but I don't think it's fully support this
I'm right?
thanks

**Comment by supersonicclay** [comment]
nebula.gl handles the user (mouse) interaction and editing of in-memory GeoJSON data. Retrieving it from a back end and sending the updates to the back end will be something you'll need to implement in your application.
