### ISSUE TITLE
Better Readme

### ISSUE THREAD

**Issue by georgios-uber** [uber/nebula.gl#44]

**Comment by IgorWilbert** [comment]
Hello @georgios-uber ! Is there anything else you would like to add on README? If so, I'd like to work on it, as I'm looking for a good first issue. Thanks!

**Comment by supersonicclay** [comment]
I think one of the most useful things the readme could include is a simple usage of `EditableGeoJsonLayer`. Also, should include a link to the documentation (at `https://github.com/uber/nebula.gl/blob/master/docs/overview.md`).

Something like:

Getting Started

```
import DeckGL from 'deck.gl';
import { EditableGeoJsonLayer } from 'nebula.gl';

const myFeatureCollection = {
  type: 'FeatureCollection',
  features: [
    /* insert features here */
  ]
};

class App extends React.Component {
  state = {
    mode: 'modify',
    selectedFeatureIndexes: [0],
    data: myFeatureCollection
  };

  render() {
    const layer = new EditableGeoJsonLayer({
      id: 'geojson-layer',
      data: this.state.data,
      mode: this.state.mode,
      selectedFeatureIndexes: this.state.selectedFeatureIndexes,

      onEdit: ({ updatedData }) => {
        this.setState({
          data: updatedData,
        });
      }
    });

    return <DeckGL {...this.props.viewport} layers={[layer]} />;
  }
}

```

**Comment by georgios-uber** [comment]
I want to make it similar to https://github.com/uber/deck.gl

I don't want to add roadmap, I want to have something that will help people get started easily.

**Comment by IgorWilbert** [comment]
Sounds good, may I send a PR for it?

**Comment by georgios-uber** [comment]
Sure
