### ISSUE TITLE
Typescript error when using Editor component

### ISSUE THREAD

**Issue by makeupsomething** [uber/nebula.gl#446]
#### Describe the bug
I get a ts error when trying to the use the `react-map-gl-draw` Editor component.

#### Actual Result
I get this output

```
TypeScript error in /Users/redacted/node_modules/@nebula.gl/edit-modes/dist-types/index.d.ts(1,1):
Declaration or statement expected.  TS1128

  > 1 | export type { EditMode } from './lib/edit-mode';
      | ^
    2 | export type { GeoJsonEditModeType } from './lib/geojson-edit-mode';
    3 | export { GeoJsonEditMode } from './lib/geojson-edit-mode';
    4 | export { ModifyMode } from './lib/modify-mode';
```
#### Expected Result

It should not give a ts error.
#### Reproduce Steps

Using the demo code provided here I am able to reproduce the error
https://github.com/visgl/react-map-gl/blob/master/examples/draw-polygon/src/app.js

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by reececasey** [comment]
+1

**Comment by reececasey** [comment]
This problem seems to occur even when using Nebula.gl directly too.

<img width="1137" alt="Screenshot 2020-07-24 at 20 45 05" src="https://user-images.githubusercontent.com/29492440/88429446-9392bf80-cdee-11ea-8ea6-628e87694c06.png">

**Comment by reececasey** [comment]
Answered my own question, TS version bumped and all working fine for me. 

@makeupsomething try bumping ts version.

**Comment by wkm97** [comment]
@reececasey 
How did you bumped ts version?
I have the same issue using nebula.gl@0.19.1.

**Comment by reececasey** [comment]
> @reececasey
> How did you bumped ts version?
> I have the same issue using nebula.gl@0.19.1.

As in your local ts version. What version of typescript do you have in your package.json?

**Comment by wkm97** [comment]
@reececasey ts version 3.6.3, need to update it?

**Comment by makeupsomething** [comment]
@reececasey Thank you! Upgrading to the latest version of typescript fixed this for me. 
@wkm97 Yes you will need to upgrade I think. The latest TS version is 3.9.7
