### ISSUE TITLE
MultiPolygon throws error in `react-map-gl-draw`

### ISSUE THREAD

**Issue by harshzalavadiya** [uber/nebula.gl#457]
#### Describe the bug
When supplying initial value in polygon Editor loads properly but when multipolygon is given editor throws error

I know drawing multipolygons might not be ideal thing but at least it should render

#### Actual Result
Throws parsing error

#### Expected Result
Should render multipolygon

#### Reproduce Steps
https://codesandbox.io/s/wispy-fog-hmrc7?file=/src/App.tsx

#### Screenshots
`Polygon`
![image](https://user-images.githubusercontent.com/5774849/89348454-350cf180-d6ca-11ea-924c-c6cd386a6b7f.png)

`MultiPolygon`
![image](https://user-images.githubusercontent.com/5774849/89348339-02fb8f80-d6ca-11ea-83b6-6b4571c05a53.png)

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by supersonicclay** [comment]
MultiPolygons are supported with `react-map-gl-draw` at this time. If you need this to work, you can try the deck.gl-based `EditableGeoJsonLayer`.
https://github.com/uber/nebula.gl/blob/master/docs/api-reference/layers/editable-geojson-layer.md

**Comment by gedion** [comment]
> MultiPolygons are supported with `react-map-gl-draw` at this time. If you need this to work, you can try the deck.gl-based `EditableGeoJsonLayer`.
> https://github.com/uber/nebula.gl/blob/master/docs/api-reference/layers/editable-geojson-layer.md
@supersonicclay - Your comment is ambiguous. Are you saying that react-map-gl-draw supports multipolygon or it does not? If not what would it take to do so?
I would like follow the react pattern but `EditableGeoJsonLayer`s have to be a direct child of deck.gl, which I'm finding limitting.

**Comment by supersonicclay** [comment]
Oops, sorry typo. I meant to say MultiPolygons aren't supported with react-map-gl-draw at this time. I am curious what limitations you're finding with deck.gl and `EditableGeoJsonLayer`.

**Comment by Bruledamien** [comment]
I am using `react-map-gl-draw`'s `Editor` inside a `MapGL` from `react-map-gl`. What is the recommended way to render MultiPolygon features alongside Polygon's (I want to keep being able to edit those by drawing) ?
