### ISSUE TITLE
How capture the click event in a mode of the editableGeoJsonLayer?

### ISSUE THREAD

**Issue by zhanghaooo** [uber/nebula.gl#460]
Hi, I'm just beginning to learn nebula.gl. I write a custom mode of the editableGeoJsonLayer，and I want to capture the double click event to prevent the map zooming in. But I find that  neither `event.stopPropagation()` or `event.stopImmediatePropagation()` is useless, could anyone help me? Thanks a lot.

**Comment by supersonicclay** [comment]
You can do this with deck.gl directly, we just don't have it in the documentation of nebula.gl yet.

https://codesandbox.io/s/lucid-poitras-sd6yl

```
 <DeckGL
      initialViewState={initialViewState}
      controller={{
        doubleClickZoom: false
      }}
      layers={[layer]}
      getCursor={layer.getCursor.bind(layer)}
    >
      <StaticMap mapboxApiAccessToken={MAPBOX_ACCESS_TOKEN} />
    </DeckGL>
  );
```
