### ISSUE TITLE
Create a line between two existing points

### ISSUE THREAD

**Issue by raj1258** [uber/nebula.gl#476]
Hi, Our requirement is to create a line between two existing points. 

We want to create two  points. Then, we want to create a line between them. I think its not possible currently. there is only polyline mode which creates a line but also creates its vertices at clicked co-ordinates. I also tried creating a line and then move it to existing points using modify mode and  snapping  but its not precise, sometimes the point also moves which we don't want to allow . Its really a blocker for us as we want to create a membership between two objects. Please explain if its possible. If its not feasible as of now. I would like to request you to please add this feature as it is really a basic use case.

**Comment by patedwards** [comment]
Hi, you could make a tool that uses the SelectionLayer to grab those pairs of points. In the onSelect method of that object you could use the pickingInfos info to get the geometries, create the line and add that line to a layer. 

The user experience would be:
- create the two points
- activate the "create pair" tool which uses the SelectionLayer
- draws a polygon or rectangle to select the points
- see a line appear between the two points

If that workflow sounds like what you're after, I could show you what I mean with a snippet but I just want to make sure that would actually solve your problem.

**Comment by supersonicclay** [comment]
nebula.gl provides the ability to create custom edit modes by extending the `GeoJsonEditMode` class. I created a simple `ConnectTheDotsMode` you can use as is or extend as you like:
https://codesandbox.io/s/connect-the-dots-mode-yow65?file=/index.js

You can also look at the built-in modes that nebula.gl provides to get more inspiration.
https://github.com/uber/nebula.gl/blob/master/modules/edit-modes/src/lib/draw-point-mode.ts
