### ISSUE TITLE
Access getFeatures, addFeatures, and deleteFeatures in functional components

### ISSUE THREAD

**Issue by kroehrs** [uber/nebula.gl#507]
If I did not provide my own features and let them be handled internally how can I access these provided methods getFeatures, addFeatures, and deleteFeatures if I'm using a React functional component and not a Class component?

**Comment by MuhmmadZohaibImtiaz** [comment]
@kroehrs  use useRef() hook and you can call these functions using 
{editorRef}.current.{function}
where editorRef is your ref hook and function is the one you want to call.
```
<Editor
   ref={editorRef}
/>
```

**Comment by kroehrs** [comment]
> @kroehrs use useRef() hook and you can call these functions using
> {editorRef}.current.{function}
> where editorRef is your ref hook and function is the one you want to call.
> 
> ```
> <Editor
>    ref={editorRef}
> />
> ```

Thank you!

**Comment by MuhmmadZohaibImtiaz** [comment]
@kroehrs you can see this example for further guide lines.
https://stackoverflow.com/questions/65735230/react-map-gl-draw-addfeatures-creating-duplicates
