### ISSUE TITLE
Obtaining bounds of rotated geojson

### ISSUE THREAD

**Issue by mogmog** [uber/nebula.gl#509]
When I use TransformMode and apply a rotate, the bounds of the geojson are the 'parent' box, ie in the diagram A,B,C,D.

![image](https://user-images.githubusercontent.com/934073/104136704-acd4fb80-538f-11eb-9a9b-8adaa2c81557.png)

How do I go about determining e,f,g,h?

**Comment by cgarrovillo** [comment]
How did you solve this?
