### ISSUE TITLE
Initial Features are not editable.

### ISSUE THREAD

**Issue by MuhmmadZohaibImtiaz** [uber/nebula.gl#510]
#### Describe the bug
Editor cannot edit initial features are given to editor.
I have read and tried sandbox example this https://github.com/uber/nebula.gl/issues/295
#### Actual Result
Unclickable Feature on map with no interaction on it.
#### Expected Result
Clicking on Feature should call onSelect and onUpdate functions and the Feature should be editable as newly created ones.
#### Reproduce Steps
Pass features to Editor component and try to modify feature on the map.
#### Screenshots
![mapunclickablefeature](https://user-images.githubusercontent.com/71523302/104575778-3bd86100-5679-11eb-95fb-aa127eddd9bc.png)

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by MuhmmadZohaibImtiaz** [comment]
I have found this Solution in https://codesandbox.io/s/react-map-gl-draw-with-initial-features-m0e97?file=/src/App.js:2733-2741.
The solution is to update state using data and no edit type should be exempt from onUpdate function.
I wasn't able to perform it because I was only updating state on editType === 'addFeature'

**Comment by DonovanCharpin** [comment]
It seems that it works with the version you are using in the codesandbox example (0.18.4) but not the last version (0.22.3). Is there something different to do?
