### ISSUE TITLE
Cannot change selected point red dot style

### ISSUE THREAD

**Issue by mahdijirofti** [uber/nebula.gl#544]
#### Describe the bug
I try to have a selected point in the map to modify. Its functionality is completely correct but I see a red dot in the center of the selected point and I cannot change the style to disable the red dot.
My props is:
```
mode: ModifyMode,
_subLayerProps: {
	geojson: {
		getFillColor: colorToRGBArray('ffffff'),
		getLineColor: colorToRGBArray('ffffff'),
		getColor: colorToRGBArray('ffffff'),
		stroked: false,
	},
},
```
How I can change style of red dot?

#### Screenshots
![Screenshot from 2021-03-13 15-28-52](https://user-images.githubusercontent.com/22638025/111029253-fcc45300-8410-11eb-9d2c-6a0096376ec3.png)

**Comment by bishoym** [comment]
There are 3 props on the `EditableGeoJSONLayer` component that'll help you achieve exactly what you need. You can find their specific implementation [here](https://github.com/uber/nebula.gl/blob/master/modules/layers/src/layers/editable-geojson-layer.ts#L145).

The props you're looking for are:
- getEditHandlePointColor
- getEditHandlePointRadius
- getEditHandlePointOutlineColor

**Comment by supersonicclay** [comment]
@mahdijirofti, you are close. nebula.gl renders multiple sublayers: `geojson`, `guides`, and `tooltips`.

You may need to use `guides` rather than `geojson` for your use case.
https://nebula.gl/docs/api-reference/layers/editable-geojson-layer
