### ISSUE TITLE
Snap on deck.gl terrain layer

### ISSUE THREAD

**Issue by Radik24** [uber/nebula.gl#596]
Is it possible to create geoJSON features snapped on deck.gl terrain layer? It always creates geoJSON features on 0 altitude.

![image](https://user-images.githubusercontent.com/23722745/120468087-23a37d00-c3a1-11eb-9493-b6fb4d027c7e.png)

Thanks

**Comment by ibgreen** [comment]
Extruding layers on terrain is one the major roadmap items for deck.gl, which has been discussed in the planning of the last couple of releases, but unfortunately we have not been able to allocate resources to it yet.

This is better discussed in deck.gl, nebula would leverage underlying support in deck.
