### ISSUE TITLE
Questions: Is it possble to move lines in EditableGeoJsonLayer were the data comes from an API. 

### ISSUE THREAD

**Issue by even996** [uber/nebula.gl#604]
Hi. 
Am new to Nebula framwork, would be nice to know more and use it. 
Is it possible to move the EditableGeoJsonLayer were the data comes from an API.
Like an attribue in EditableGeoJsonLayer onSelected: { scaled: 5, position: 10 } or getSelected: d => d.geomtry[50,50]

I found some examples for moving it around, but that was for lines that was created with drawPolygonMode.
Is it possible to disable draw polyline too? 

My code:  Renders the layers fine. 
` return( new EditableGeoJsonLayer({
        id: 'geojson-layer ',
        data: geojson,
        pickable: true,
        stroked: false,
        filled: true,
        extruded: true,
        autoHighlight: true,
        extensions: [new PathStyleExtension({offset: true})],
        getOffset: object => getOffsetLines(object),
        lineWidthScale: 2,
        lineWidthMinPixels: 3,
        getFillColor: [200, 200, 100],
        getLineColor: d => getColorForLine(d, showOccupancy, showFrequency),
        getLineWidth: 1,
        getElevation: 30,  
        highlightColor: [0,255,128,255],
    }));
`

**Comment by jfuehner** [comment]
@even996 Yes it is possible to move LineStrings. Take a look at the nebula GeoJSON editor [example ](https://nebula.gl/geojson-editor/). Specifically, select the LineString and then select the _Alter Mode_ "Modify" or "Extend LineString". 

Additionally, nebula makes it fairly easy to extend or implement your own Editing [Modes](https://nebula.gl/docs/api-reference/modes/overview).

**Comment by even996** [comment]
@jfuehner  Cool this is what I wanted. 
I have been looking at this example https://nebula.gl/docs/api-reference/layers/editable-geojson-layer . Been trying to replicate this with TranslateMode.  With no luck. Is there something else i need to provide. If I add the attribute mode: TranslateMode i get some undefined errors in 'TranslateMode.isSelectionPicked'.  But atleast is giving me feedback when hovering the feature. 

Thanks a ton for the help :) 



 mode: DrawPolygonMode,
      selectedFeatureIndexes,
      onEdit: ({ updatedData }) => {
        this.setState({
          data: updatedData,
        });
      }

**Comment by jfuehner** [comment]
Can you put together a sample via Codepen, StackBlitz, CodeSandbox, etc so I can better assist?

**Comment by even996** [comment]
@jfuehner  Took some time.  First time doing CodeSandbox. If you hover the line the error will show. 
Just have look when you have the time, thanks again.

Code -->  https://codesandbox.io/s/naughty-shtern-td0mb?file=/src/App.js

**Comment by jfuehner** [comment]
@even996 your `EditableGeoJsonLayer` is missing the `selectedFeatureIndexes` property. 

I had a similar issue (#550) a while back because the nebula docs say the prop is optional.

**Comment by even996** [comment]
@jfuehner  Ye you're right when adding `selectedFeatureIndex` propery the error went away.
I'm still not able to drag the line. Do you know if there is anything else am missing?

**Comment by jfuehner** [comment]
@even996 you will need to implment the `onEdit` function of the `EditableGeoJsonLayer` _(See [docs](https://nebula.gl/docs/api-reference/layers/editable-geojson-layer))._ Then update your state based on the `updatedData` provided via the callback.

**Comment by even996** [comment]
@jfuehner  Je i tried to make it work with the onEdit function . It works for the mode `DrawPolygonMode`. 
But not for the `TranslateMode`.

Updated code. --> https://codesandbox.io/s/naughty-shtern-td0mb?file=/src/App.js

**Comment by jfuehner** [comment]
@even996 The `DrawPolygonMode` operates differently than the `TranslateMode`. The `DrawPolygonMode` draws its points/lines internally to nebula. For the `TranslateMode` you will need to will need to implement the `onClick` event as well for the `EditableGeoJsonLayer `. 

Within the `onClick` you will need to update the `selectedFeatureIndexes` array to the index of the `object` within your `geojson2` array. Then within the onEdit you need to continuously update the state based on the edited/moved object data.

The idea is you are telling nebula what object(s) have been selected and then as they change you tell deck/nebula to re-render/update state.

**Comment by even996** [comment]
@jfuehner  Got it, know I understand a bit more of the differenes between those two modes. 

1) So I need to put the geojson data inside a useState. 
2) Then add onClick method  to select the differenent features. 
3) Then add onEdit to update the geojson state for the selectedFeature from the onClick method. 

Again thanks alot for helping out :)
