### ISSUE TITLE
Requesting example usage for editMode: ModifyMode

### ISSUE THREAD

**Issue by neelduttahere** [uber/nebula.gl#608]
Hi, 
This may sound a bit stupid, but I am trying to use `ModifyMode` under the `mode` property of EditableGeoJsonLayer, but the adjustable handles do not appear, as it is supposed to in the "Geojson Editor" example posted on nebula.gl website. It would have been convenient if there were more examples regarding the editableGeojsonLayer API reference. This what I am trying to do:

```javascript
new (EditableGeoJsonLayer as any)({
            id: 'geojson',
            data: featureState.data,
            mode: ModifyMode,
            selectedFeatureIndexes,
            onEdit: ({updatedData}):any => {
                setFeatureState({ 
                    data: updatedData 
                });
                
            },
            pickable: true,
            pickingRadius: 15,
            //onClick: data => InfoWindow(data.object.properties, data.coordinate, "New Shape", "PointView"),
 })
```

Also after further tests, none of alter modes are working, but all draw modes and view modes are working fine

**Comment by neelduttahere** [comment]
I also noticed that a lot of files under `@nebula.gl/edit-modes/src` have typescript related errors, I am trying to solved them. Could this be the reason why ModifyMode is not working for me?

**Comment by neelduttahere** [comment]
Okay I have solved it. I think there should be more clarity in the documentation on how to handle altermodes of this library. I will contribute to update it. For now this is how to go about it:

1.  In order to use alter-modes (eg: scaleMode, modifyMode, etc, see mode overviews from the official documentation), you have to update the `selectedFeatureIndexes` after you have completed the operation of drawing a feature/completing a shape. You can handle this event by using the `editType` argument of the `onEdit` function of the `editableGeoJsonLayer`, and use the `editContext` argument to fetch the current selected feature indexes and also to use the same to update your `selectedFeatureIndexes` state. Only after doing this you render the editHandles to edit your features that was drawn.

**Comment by Teyae** [comment]
You should make sure the feature is selected ,as a matter of fact make it can be seleted at first.
