### ISSUE TITLE
Editable GeoJSONs on website not working

### ISSUE THREAD

**Issue by trevorwhealy** [uber/nebula.gl#63]
I think you may need to downgrade your Deck.gl version or upgrade to their new standard for using Views/ViewState in place of Viewport.

https://neb.gl/#/examples/editable-geo-json/points

<img width="1461" alt="screen shot 2018-08-30 at 11 08 22 am" src="https://user-images.githubusercontent.com/14946478/44870418-0e73ef80-ac45-11e8-9f33-26c8238d4e67.png">

**Comment by georgios-uber** [comment]
Thanks for the report.

I was focusing on the homepage "Hero" demo. I'll fix those demos soon.

**Comment by trevorwhealy** [comment]
Thanks @georgios-uber - the homepage "Hero" demo is awesome!

**Comment by georgios-uber** [comment]
Fixed in https://github.com/uber/nebula.gl/commit/b97c3e410d3fd42db67d722aa96dc1651b661759

Improved existing demos and also **added a new demo**.
