### ISSUE TITLE
PathMarkerLayer not working with deck.gl 8.6.0

### ISSUE THREAD

**Issue by Radik24** [uber/nebula.gl#662]
#### Describe the bug
Hi, I'm trying to implement PathMarkerLayer, but it seems to be broken if using deck.gl 8.6.0
#### Actual Result
![image](https://user-images.githubusercontent.com/23722745/141136313-f4a748eb-c2dd-4e91-9c57-29aa2488cf5d.png)
#### Expected Result
Working PathMarkerLayer
#### Reproduce Steps
My cody is basically copy-paste from examples

Also `_subLayerProps.geojson._subLayerProps.line-strings` changed to `_subLayerProps.geojson._subLayerProps.linestrings`

```
new EditableGeoJsonLayer({
  id: 'geojson',
  data: {
    type: 'FeatureCollection',
    features: [
      {
        type: 'Feature',
        properties: {
          stroke: '#ff0000',
          'stroke-width': 10,
          'stroke-opacity': 1
        },
        geometry: {
          type: 'LineString',
          coordinates: [
            [
              -122.40880966186523,
              37.783536601521924
            ],
            [
              -122.43893623352051,
              37.779669924659004
            ],
            [
              -122.43515968322752,
              37.7624370109886
            ],
            [
              -122.42348670959471,
              37.77180027337861
            ],
            [
              -122.4250316619873,
              37.778584505321376
            ],
            [
              -122.42314338684082,
              37.778652344496926
            ],
            [
              -122.42357254028322,
              37.77987343901049
            ],
            [
              -122.41198539733887,
              37.78109451335266
            ]
          ]
        }
      }
    ]
  },
  _subLayerProps: {
    geojson: {
      getLineWidth: 10,
      lineWidthUnits: 'pixels',
      lineCapRounded: true,
      lineJointRounded: true,
      _subLayerProps: {
        'linestrings': {
          type: PathMarkerLayer
        }
      }
    }
  }
})
```

Don't know if https://github.com/uber/nebula.gl/pull/660 will fix it, I can't install that branch somehow

Thanks!

**Comment by Radik24** [comment]
Hi, I installed new version and all ^^ issues seems to be solved :)

How exactly should PathMarkerLayer work? It seems it makes lines much thicker

![image](https://user-images.githubusercontent.com/23722745/143067778-618150d2-f66d-444f-a4f1-003d279d2e55.png)

using PathMarkerLayer:
![image](https://user-images.githubusercontent.com/23722745/143067533-89c59d3f-5d3e-456c-999f-a6f8fb8391d2.png)

Also in example it is much thicker
![image](https://user-images.githubusercontent.com/23722745/143067874-81c79671-1b93-47a8-9184-42e3d0dfc4d2.png)

Thanks

**Comment by igorDykhta** [comment]
Most likely it is related to used units: common/meters/pixels. I'll investigate.

**Comment by igorDykhta** [comment]
The fix should be on master.
Meters are now selected as default units.
With custom layer you need to provide sub layer props like this (based on how marker layer is implemented right now):

```
_subLayerProps: {
        geojson: {
          getLineWidth: 5,
          lineCapRounded: true,
          lineJointRounded: true,
          _subLayerProps: {
            linestrings: {
              type: PathMarkerLayer,
              _subLayerProps: {
                paths: {
                  widthUnits: 'pixels',
                },
              },
            },
          },
        },
      },
```

**Comment by Radik24** [comment]
Thank you :)
