### ISSUE TITLE
Redirect http to https for neb.gl

### ISSUE THREAD

**Issue by supersonicclay** [uber/nebula.gl#67]
http://neb.gl is giving stale content

**Comment by supersonicclay** [comment]
This will fix #2

**Comment by georgios-uber** [comment]
But I fixed it already.

**Comment by supersonicclay** [comment]
I'm talking about these:

* http://neb.gl/#/examples/editable-geo-json/points
* http://neb.gl/#/examples/editable-geo-json/polygons

**Comment by georgios-uber** [comment]
Yes, they are fixed now.

**Comment by supersonicclay** [comment]
Ah, it is the http vs https issue. I'll retitle this to fix http caching.

**Comment by supersonicclay** [comment]
No longer able to repro. Closing.
