### ISSUE TITLE
react-map-gl-draw EditingMode: undo?

### ISSUE THREAD

**Issue by brendanatme** [uber/nebula.gl#754]
#### Background 

Hi, great project you've all put together here. I'm using the `react-map-gl-draw` library in `EditingMode`, and I want to add the ability for users to undo edits they've made (to be clear, not resetting all edits entirely, but undoing each incremental edit one-by-one). Does the library provide a way to do this? I've looked through the documentation but haven't found anything. After viewing the source code, no undo functionality seems apparent to me there either.

Nonetheless, if there is any way to implement undo functionality, could you tell me how? Can you document it? And if not, do you have any plans to add this functionality?

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Doc update
  - [ ] Test

**Comment by alexvarney** [comment]
I've done this with Nebula using mobx-state-tree and their [history tracking middleware](https://github.com/mobxjs/mobx-state-tree/tree/master/packages/mst-middlewares). The approach that I took was making my map a controlled component and handling certain onEdit event types and marking them as a 'significant' point that I may want to jump back and forward to. I believe there's a pretty straightforward way to do with with Redux as well.

**Comment by brendanatme** [comment]
I see, that makes sense. Thanks!
