### ISSUE TITLE
bug with function EditableGeoJsonLayer.getCursor()

### ISSUE THREAD

**Issue by linze99** [uber/nebula.gl#786]
after deck.gl update to 8.8.0+,my propram raise a exception like this:
![1](https://user-images.githubusercontent.com/30024479/180605533-309f1b05-5e61-432a-beb4-d70bb7232564.JPG)
it happend in the function EditableGeoJsonLayer.getCursor(),
![2](https://user-images.githubusercontent.com/30024479/180605534-d2fe3195-129f-4950-8db4-3294e2efbc7e.JPG)
at the mean time this.state is undefined but not null;

after changed the code with:
```js
  if (this.state === null || this.state === undefined) {
    // Layer in 'Awaiting state'
    return null;
  }
```
it works fine

**Comment by Prestaul** [comment]
@linze99 are you on React 18? I ran into the same issue and I'm wondering if it could be related to automatic batching in React 18.
