### ISSUE TITLE
Types broken after install nebula.gl

### ISSUE THREAD

**Issue by adriangonzalezrodrigo** [uber/nebula.gl#801]
#### Describe the bug
For example, I use the next versions of deck.gl and react-map-gl

    "@deck.gl/core": "8.6.0",
    "@deck.gl/extensions": "8.6.0",
    "@deck.gl/geo-layers": "8.6.0",
    "@deck.gl/layers": "8.6.0",
    "@deck.gl/mapbox": "8.6.0",
    "@deck.gl/mesh-layers": "8.6.0",
    "@deck.gl/react": "8.6.0",
    "react-map-gl": "^7.0.19",

The types like:
import { DeckGLRef } from '@deck.gl/react';
import { InteractionState } from '@deck.gl/core';
import { ViewStateChangeEvent } from 'react-map-gl';
import { LayersList } from '@deck.gl/layers';

are ok.

But when I install nebula.gl 1.0.3 and the postinstall scripts runs, the above types are missing.

But, if I execute again the npm i, the types are ok again.

#### Actual Result
Types are missing.

#### Expected Result
The types shouldn't be missed.

**Comment by timnyborg** [comment]
The [layers package file](https://github.com/uber/nebula.gl/blob/863abedef4d78bb369a7f69fb47a290f369b8aa6/modules/layers/package.json) has the old types library as a dependency: `"@danmarshall/deckgl-typings": "4.9.12",`
This is incompatible with the types in deck.gl >=8.8

**Comment by abouroubi** [comment]
@timnyborg I hope your PR will be merged.
The same PR was opened few months ago; it was never merged...

**Comment by Akiyamka** [comment]
Merged
